name = "yusak-todolist"
pages_build_output_dir = "./dist"
compatibility_date = "2025-06-24"
main = "api/index.js"

[[d1_databases]]
binding = "DB" 
database_name = "todo-db"
database_id = "4a860e41-9b4d-4648-947f-6e453b51606b"