name = "yusak-todolist"
compatibility_date = "2025-05-05"

main = "api/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "todo_db"
database_id = "2ee72edd-6f0f-40e6-bc1b-7af1fa91f126"

migrations_dir = "./migrations"